# Generated by Django 5.2.9 on 2026-03-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="qty",
            field=models.IntegerField(null=True),
        ),
    ]
